### ISSUE TITLE
regress out CSF/WM/GS/motion from preprocessed data before calculating ALFF/ReHo and extract time series from atlas 

### ISSUE THREAD

**Issue by ilyaveer** [mindandbrain/pipeline#10]
Instead of directly inputing preproc.nii.gz into the ALFF/ReHo workflow or extracting time series from the (masked) atlas regions, now first:

fsl_glm -i <preproc.nii.gz> -d <CSF/WM/GS/motion signals> -o <whatever> --out_res=<residual 4D file>

The residual 4D file is the preprocessed data with the confound signals regressed out, which can now be inputted into the ALFF/ReHo workflow, or from which the time series from the masked atlas regions can be extracted.

**Comment by marcbue** [comment]
implemented first version on branch dev_m,
if this works I'll implement it for ALFF too.

Regarding Brainatlas_wf:
Currently we do the following here:
fslmaths (inputs: atlas, mask file (-mas)) - output_1
fslmeants (inputs: preproc.nii.gz, output_1 (--label)) - output_brainatlas_matrix

Am I right that we want to change it to the following?
fslmaths (inputs: atlas, mask file (-mas)) - output_1
fsl_glm -i <preproc.nii.gz> -d <CSF/WM/GS/motion signals> -o --out_res=<residual 4D file>
fslmeants (inputs: <residual 4D file>, output_1 (--label)) - output_brainatlas_matrix

**Comment by marcbue** [comment]
implemented now for reho, alff, brainatlas
