### ISSUE TITLE
add flag for group analysis only

### ISSUE THREAD

**Issue by ilyaveer** [mindandbrain/pipeline#17]
This should circumvent that the pipeline first checks whether all fmriprep/nipype output is generated, and just runs the higher level stats on the features that are in the pipeline.json. This way, people could remove the entire nipype folder after preprocessing to save space.

Can we jump to the higher level routines bypassing the fmriprep parts?

**Comment by marcbue** [comment]
create a flag that only the files in the intermediates folder are used for the higherlevel analysis.

Take files from intermediates folder for the inputnode in stats.py

inputnode = pe.Node(
        interface=niu.IdentityInterface(
            fields=["copes", "varcopes", "dof_files", "mask_files", "zstats"]
        ),
        name="inputnode"
    )


and skip the firstlevel part in run.py
