### ISSUE TITLE
Enable multiple templates for ICA Maps

### ISSUE THREAD

**Issue by marcbue** [mindandbrain/pipeline#19]
Change question to ICA Maps
Do you want to to do ICA Maps (Dual Regression)?
     Give a name.
     Give the path.
  Do you want to add another ICA Map? (Yes/No)
     Give a name.......

Add indentation to pipeline.json. Similar to brainatlas.
Enable multiple processing in the pipeline so several ICA Maps can be processed.

**Comment by marcbue** [comment]
Fixed the error that Ilya came across. I merged the changes into dev now. Can be tested.
@ebohorqu:
I also adjusted the file_checks.py to check for the files created due to multiple ICA templates.

**Comment by ilyaveer** [comment]
That’s great news! Thanks so much for solving this Marc! I will test it asap.
Cheers,
Ilya
