### ISSUE TITLE
change csf_wm_meants, gs_meants for reho/alff

### ISSUE THREAD

**Issue by marcbue** [mindandbrain/pipeline#20]
Currently the csf_wm_meants, gs_meants files that are used for the confounds are calculated with the preproc.nii.gz. (see in firstlevel.py connection between maskpreproc and csf_wm_meants node for example).
For reho and alff these files should be calculated based on:

input (/subject/task_rest/func_preproc_01_rest/ica_aroma_wf/ica_aroma/out/denoised_func_data_nonaggr_tempfilt.nii.gz) after bandpass filtering!
so inputnode/bandpass (inputfile --> bandpass_filtered file)

Take the bandpass filtered file and calculate csf, wm, gs and then put it into glm

**Comment by marcbue** [comment]
Question:
The current workflow uses the preproc.nii.gz for calculating csf_wm_meants and gs_meants. We use these files for creating the design matrix for the glm, where output "out_res" is then given to the bandpass filter.
Since the bandpass filtered file should be used now to calculate csf_wm_meants and gs_meants what do we put as a design into glm?
Or should these timeseries be calculated on the unfiltered file?

![image](https://user-images.githubusercontent.com/44844855/60393602-61922980-9b18-11e9-9be5-0a16d250bf24.png)

**Comment by marcbue** [comment]
This is now implemented for reho and alff.

One question to the implementation for alff:
We have two nodes for (I guess) standard deviation for filtered and unfiltered files in alff, which are the main images that are used in alff. I implemented it now in this way:
Unfiltered file as input to node stddev_unfltrd (This is before any glm! So no interaction with csf/wm/gs)
GLM.out_res as input to node stddev_fltrd (This is after glm with the filtered file and csf/wm/gs based on the filtered file as input to the glm)

Is this what you wanted?

**Comment by ilyaveer** [comment]
This is a good catch! I actually did not think about doing confound regression for both the filtered and unfiltered files, which we need to do...! So I would make the alff workflow as follows:

denoised_nonaggr.nii.gz -> csf/wm/gs -> design -> glm -> bandpass -> stddev_filtered (=alff)

denoised_nonaggr.nii.gz -> csf/wm/gs -> design -> glm -> stddev_unfiltered

then stdev_filtered/stdev_unfiltered (=falff) 

For ReHo it should then similarly:

denoised_nonaggr.nii.gz -> csf/wm/gs -> design -> glm -> bandpass -> ReHo

**Comment by marcbue** [comment]
changes implemented
