### ISSUE TITLE
Implement within Group design

### ISSUE THREAD

**Issue by marcbue** [mindandbrain/pipeline#22]
1. Further adjust questions in interactive part. (See handwritten notes)
![WhatsApp Image 2019-06-22 at 8 42 22 AM](https://user-images.githubusercontent.com/44844855/60127666-103d0f80-9791-11e9-8c90-ed789859fccf.jpeg)

2. Implement within group design in pipeline.

**Comment by marcbue** [comment]
Next Step: how do we do the higherlevel workflow right now for the across all subject analysis?
What would we need to do for the within group analysis

**Comment by ebohorqu** [comment]
1. Merging of only specific files? or merging is done for all specific files?
- Depending on the groups that are specified in the pipeline.json, the merging has to be done accordingly for each group that is defined there.
- Use code of excluded subjects (base.py)
2. Set up of model
- Between groups: same model
- Within groups: same model, different constrast
--Same model:
One column: 1 for all columns (One-sample t-test)
Second column: Continuous variable demeaned
Other columns: Covariates demeaned
--Contrast is different! 
0 (-1)1 0 0 (-1 or +1 for continuous variable, 0 for others)
Create a new contrast (similar to contrast of one-sample t-test)
2 contrasts: +1, -1 on the continuous variable
3. Folder structure or longer names for different processes (between and within group)

**Comment by ebohorqu** [comment]
@ilyaveer, in the questionnaire of within group comparison now we can select different combinations of groups to create different models, but I wonder if the same covariates should be shared or not. The questions are now like this:
1. Select continuous variable
2. Select different combinations of groups
3. Select covariates (Here the same covariate columns are used for all the models for the specified continuous variable)

Or it should be something like:
1. Select continuous variable
2. Select one combination of groups
3. Select covariates
4. Repeat?
In the last case, for each combination of groups a different set of covariate columns can be selected (they are not shared between models).

What is the right option?

**Comment by ilyaveer** [comment]
I think we should make it flexible, so that different covariates could be
used for different within-group models.
Thanks!

**Comment by ebohorqu** [comment]
Ok, now the code is more flexible. In the json file, under WithinGroup there is a dictionary per model  (with a name that includes the continuous variable and the group(s) selected). Each model includes the values of both the continuous variable and the covariates.  Could you check the excerpt of the pipeline.json and tell me if that is fine? Thanks!

[group_design_pipeline.json.txt](https://github.com/mindandbrain/pipeline/files/3728959/group_design_pipeline.json.txt)

You can see also the questions and answers used to generate that json file. This is in the screenshot:

<img width="1280" alt="Screen Shot 2019-10-15 at 1 11 30 PM - Group design " src="https://user-images.githubusercontent.com/13590349/66827223-a074af80-ef4e-11e9-8e22-5da3921b3dca.png">

**Comment by ilyaveer** [comment]
Hi Eliana,

This looks good! I'm just wondering whether we need the name of the
continuous variable in the within-group model identifier (e.g. sex_UPD
and age_UPD_CTRL). Why not just the groups selected as name?

Cheers,
Ilya

**Comment by ebohorqu** [comment]
@ilyaveer I think we need a combination of the continuous variable and the group in the key of the dictionary in case we want to have two different models with the same group but two different continuous variables. And we need a unique key for each model. Does this make sense? or would this be possible?

ex. We can have age_CTRL and sex_CTRL

**Comment by ilyaveer** [comment]
your absolutely right, one step ahead! :)

**Comment by ebohorqu** [comment]
good!

**Comment by ebohorqu** [comment]
* One-sample t-test needs to be skipped (given it can be replaced by an appropriate contrast). For this remove 2 blocks of code:
** # option 1: one-sample t-test (level2model without covariates)
** # one-sample t-test with covariates (level2model with covariates)

* When user says not to do any group design, don't run init_higherlevel workflow in base.py

* Only two kinds of processing are done, between or within group comparison. They are not exclusive.

* nipype: prefix for kind of processing. No additional folders are created

* Additional question for between group comparison: Selection of covariates. Data is taken from pipeline.json, so no more changes are needed.

* Add additional dictionary of "SubjectGroups" for each within group model (of course only with the subset of required subjects)

* Processing for within group comparison:
Reuse one-sample t-test and between group model code to:
** Build a design matrix: regressors: demeaned continuous variable, demeaned covariates and column of 1s for all subjects.
** Build two contrast vector: contrasts: 1 and -1 for continuous variable, 0 for all other columns.

**Comment by ebohorqu** [comment]
@marcbue, @ilyaveer, could you send a picture of the sheet of paper we worked on last week?

@ilyaveer, the current code only performs the two-sample t-test (or between group comparison) when there are covariates. But we should be able to create the model, even if there are no covariates, using only the group membership, right? This is what we should do in that case?

Thanks!

**Comment by marcbue** [comment]
![IMG_20191023_112936](https://user-images.githubusercontent.com/44844855/67379176-b60a5a80-f588-11e9-96db-437600772344.jpg)

**Comment by ilyaveer** [comment]
Correct!

**Comment by ebohorqu** [comment]
@ilyaveer, do we need to include the column of ones for the model of within group comparison even  if we demean the continuous variable and the covariates?
Also, just to confirm, in the two contrasts in within group comparison, the 1 (-1) is for the continuous variable, otherwise 0. Right?

**Comment by ilyaveer** [comment]
See below!

> Op 23 okt. 2019 om 14:06 heeft ebohorqu <notifications@github.com> het volgende geschreven:
> 
> ﻿
> @ilyaveer, do we need to include the column of ones for the model of within group comparison even if we demean the continuous variable and the covariates?
> 
Yes.

> Also, just to confirm, in the two contrasts in within group comparison, the 1 (-1) is for the continuous variable, otherwise 0. Right?
> 
Yes. :)

**Comment by ebohorqu** [comment]
@ilyaveer, could you send me a text file with the folder and file names of the output generated by the pipeline when a task and a between group comparison is specified? It can be an excerpt, it does not need to be all the folders and files. I need to see what nipype creates! Thanks!

**Comment by ebohorqu** [comment]
@ilyaveer, I made several changes to the code addressing all the things we talked in the last meeting. 
Could you please use the code in branch **dev_group_design** and set up some tests? Basically, we need to test that the code does not crash with any of the possible configuration settings, it finishes successfully all specified workflows and it generates the correct output.

In particular:
* Between group and (several) within group comparisons can be performed in one run
    * Folder/file hierarchy is fine
* Within group comparisons are done correctly:
    * Expected workflows/output
    * Only subjects of selected groups are used
* Covariates can be selected for between group comparison
* Between group comparison can be done without covariates (only subject id and subject group are provided)
    * No one-sample t-test is performed
* Second level statistics do not run if user answers “No” to "Specify a group-level design?" 
    * No one-sample t-test is performed
    * First level statistics are calculated successfully 

Please be sure to have the right code, you should be able to confirm this if the interactive questionnaire contains all the options we discussed (e.g. specify a group-level design?, specify between group comparison? specify within group comparison?)

Thanks!!

**Comment by ilyaveer** [comment]
As dev (or any version based on dev) currently does not run on my pc, I cannot test whether the output is correct. The menu works well, and the correct values are used in pipeline.json.

@marcbue could you perhaps test the group stats on your pc, using an output folder that has preprocessed data?

**Comment by ebohorqu** [comment]
@ilyaveer, this branch is based on a previous dev version, so maybe it runs on your computer, but I am not sure.

@marcbue, could you set up a test? For this one you can specify both a between group and a within group comparison. Or just to be on the safe side, maybe first a test only with a within group comparison and then another with both of them. There are no restrictions on the parameters that you need to select (e.g. you can select all covariates you want, or groups, etc).
Many thanks!!!

**Comment by ebohorqu** [comment]
@ilyaveer, could you provide us with a good spreedsheet for specifying a group design?.  The ones I have do not have any continuous variable, for instance. This is for running a realistic test. Thanks!
