### ISSUE TITLE
nipype alff filename too long

### ISSUE THREAD

**Issue by ilyaveer** [mindandbrain/pipeline#26]
raise OSError('Could not create directory %s' % path)
OSError: Could not create directory /ext/scratch/punim0564/test_24June/nipype/_hp_0.009/_hp_0.009/_hp_0.009/_hp_0.009/_hp_0.009/_hp_0.009/_hp_0.009/_hp_0.009/_hp_0.009/_hp_0.009/_hp_0.009/_hp_0.009/_hp_0.009/_hp_0.009/_hp_0.009/_hp_0.009/_hp_0.009/_hp_0.009/_hp_0.009/_hp_0.009/_hp_0.009/_hp_0.009/_hp_0.009/_hp_0.009/_hp_0.009/_hp_0.009/_hp_0.009/_hp_0.009/_hp_0.009/_hp_0.009/_hp_0.009/_hp_0.009/_hp_0.009/_hp_0.009/_hp_0.009/_hp_0.009/_hp_0.009/_hp_0.009/_hp_0.009/_hp_0.009/_hp_0.009/_hp_0.009/_hp_0.009/_hp_0.009/_hp_0.009/_hp_0.009/_hp_0.009/_hp_0.009/_hp_0.009/_hp_0.009/_hp_0.009/etc.

**Comment by marcbue** [comment]
Is fixed in dev.
Should I fix this directly in master too?

**Comment by ilyaveer** [comment]
Will test this and other dev changes tomorrow. If all okay, we just merge it with master.

**Comment by ilyaveer** [comment]
seems to be solved!
