### ISSUE TITLE
Remove first column of demeaned_covariates.csv

### ISSUE THREAD

**Issue by marcbue** [mindandbrain/pipeline#28]
The created demeaned_covariates file has an additional indexing column, that should be removed for the actual demeaned_covariates file

**Comment by marcbue** [comment]
the demeaned covariates file doesn't have this first index column anymore.
@ebohorqu 
Can this be merged or do you need to make changes to your code now, that the column is gone?

PS: Code is in branch Issue #28

**Comment by ilyaveer** [comment]
@ebohorqu, can you answer this please so we can close the ticket?

**Comment by ebohorqu** [comment]
If this refers to the file loaded under the variable “spreadsheet_file” during setup, I consider the two cases: when there is indexing and when not. In that case there is no additional change needed. 
If it refers to another file, I don’t think I have used it.

**Comment by marcbue** [comment]
I close this then. This does actually refer to another file that is created in stats.py. We were just wondering why there is an additional index column if compared to the "spreadsheet_file". If you don't use the demeaned_covariates file then this should be fine. Code is already in dev.

**Comment by ebohorqu** [comment]
I think there could have been an index column in demeaned_covariates because the same column was also present in the spreadsheet_file before.
