### ISSUE TITLE
NaN values in covariates sheet

### ISSUE THREAD

**Issue by ebohorqu** [mindandbrain/pipeline#29]
People are instructed to set NaN or n/a to indicate there is a missing value.

NaN values should be ignored for demeaning. After that they should be replaced by zero for the following analysis (regression models) and the demeaned covariates file.

**Comment by marcbue** [comment]
NaN or n/a strings in the datasheet now will be ignored for demeaning and afterwards be replaced by 0 for regression and the demeaned covariates file. Please test this on branch Issue#29 (Don't confuse it with branch Issue#28). I get an error currently but it is one I had in the past where your dataset didn't get one. My dataset unfortunately doesn't have covariates.
