### ISSUE TITLE
Exclude subjects based on Movement

### ISSUE THREAD

**Issue by marcbue** [mindandbrain/pipeline#32]
Add a question to the CLI:
Do you want to exclude subjects based on Movement?
  Set the threshold for the average FramewiseDisplacement: (Standard is 0.5)
  Set the threshold for the percentage of volumes larger than 0.5: (Standard is 10%)

After first run of pipeline:
Create a new file called motion_report.csv in qualitycheck.
In there:
Column1 - ID (Subject ID)
Column2 - Mean_FD (Average of FramewiseDisplacement in confounds_mni.tsv, Ignore the empty row for meaning)
Column3 - %volume_lg_0.5 (Count all rows of FramewiseDisplacement that have a value larger than 0.5, Calculate the percentage with respect to the total amount of volumes (rows))
Column4-9 - Max_X, Max_Y, Max_Z, Max_RotX, Max_RotY, Max_RotZ (Maximum values of corresponding columns in confounds_mni.tsv)

Add excluded subjects for higherlevel analysis based on:
Mean_FD > Chosen Parameter (see above)
%volume_lg_0.5 > Chosen Parameter (see above)
add these subjects to function get_qualitycheck_exclude in qualitycheck.py

@ebohorqu 
This will affect the file checks as there is a new file in qualitcheck

**Comment by ilyaveer** [comment]
Tested, runs through, and motion file is created. However, the one subject with above-threshold movement submitted to the pipeline was in the end not excluded for the group analyses. Also, all subjects are still included in the demeaned_covariates file.

**Comment by marcbue** [comment]
can be tested, subjects should now be excluded, only works if motion_report exists (if it not exists we need a first run to get it created and then a second run to get subjects excluded)
if tested and works I will merge into dev and close this ticket

**Comment by marcbue** [comment]
Check whether it is necessary to run the whole pipeline once to create the motion_report and run again to exclude subjects or if this can be included into one run
