### ISSUE TITLE
might want to consider using reprozip to minimize docker image

### ISSUE THREAD

**Issue by yarikoptic** [mindandbrain/pipeline#35]
ATM docker image is whooping 12GB. If you have a number of sample use cases you might want to consider https://www.reprozip.org/ . Here is some assistance via neurodocker: https://github.com/kaczmarj/neurodocker/#minimize-existing-docker-image

Cheers

**Comment by HippocampusGirl** [comment]
Considering the file sizes usually involved in processing neuroimaging data, 12GB can not be considered a lot. In any case, thank you for the idea :-)
