### ISSUE TITLE
Block parallelization for servers 

### ISSUE THREAD

**Issue by trislett** [mindandbrain/pipeline#5]
Two options:
(1) Subject specific job initiation
(2) Block of jobs with subject subsets

Potential problems:
- writing/re-writing of shared files leading to job failures
- this could be solved be each job having their own folder which is later merged (may cause other issues)

To-do:
- logging of the pipeline at each stage
- create list of files that are created at each stage, and their size (for debugging the time each stage took would also be helpful)
- add sanity check prior to group level analyses (either using files, logs or both)

**Comment by ebohorqu** [comment]
Now the code (in branch dev) accepts an additional parameter (--jsonfile) for execution of single subject analysis (first level statistics) using json files located at dir workdir/json_files and which are generated by the code if the flag --setup-only is given.

**Comment by ebohorqu** [comment]
@ilyaveer I am wondering what are the keys in the metadata section of pipeline.json that are required for first level analysis, no matter if the workflow is rest or task. And how we want to deal with differences between these two cases. This is for the proper creation of the individual (or block) json files.

In the case of a rest workflow I have the next keys: "TemporalFilter", "SmoothingFWHM" and rest. And in the case of a task workflow: "TemporalFilter", "SmoothingFWHM" and the name of the task, which could vary (as "faces")?  Are more keys in the metadata section needed for the first level statistics?

Or in a similar way, what are the keys in the metadata that are not needed for first level analysis? 
"SubjectGroups", "GroupContrasts" and "Covariates" are all of them?

**Comment by trislett** [comment]
@ebohorqu how is it going with this?

**Comment by ilyaveer** [comment]
This all works now!
