### ISSUE TITLE
In interactive part enable choosing which confound regressors to use in first-level stats 

### ISSUE THREAD

**Issue by ilyaveer** [mindandbrain/pipeline#7]
For both task and rest workflow ask which of the following confound regressors people want to include in the GLM: CSF signal, WM signal, Global signal (= CSF+WM signal together), motion parameters (which are 6 regressors).

Best to use the confound signals extracted after all preprocessing has been done (see other issue). Set up code to use any combination of these confounds (important, motion is always used as all 6 regressors together, so no need to ask which of these six to use) to be added to the GLM. 

Do the confound regressors need to be demeaned, or is this automatically taken care of when using film_gls?

**Comment by marcbue** [comment]
Implemented on branch dev_m.
Please test and also check for demeaning.

**Comment by marcbue** [comment]
Add support for regression extracted from preproc.nii.gz and mask.nii.gz.

See #6

**Comment by ilyaveer** [comment]
Before extracting time series from seed mask/Atlas/ICA components (and CSF/WM):

fslmaths <atlas/seed/ICA file> -mul <brain_mask_mni> <atlas/seed/ICA masked>

instead of using the seed/atlas/ICA file provided by the user in the interactive menu, we now take the bold_mask_mni masked version of these files when using fsl_meants (with either --label or -m option for brain atlas and seed connectivity, respectively).

**Comment by marcbue** [comment]
done
