### ISSUE TITLE
Remove manual entry of TR in interactive part

### ISSUE THREAD

**Issue by ilyaveer** [mindandbrain/pipeline#8]
Read repetition time (TR) from nifti file directly. It should not be specified by user manually anymore, as different data with different TRs can (and likely will) be used by any one site at the same time.

**Comment by marcbue** [comment]
Can be tested.
Branch: dev_m

**Comment by ilyaveer** [comment]
read TR from 4D nifti file:

fslinfo <4D file> | grep pixdim4

**Comment by marcbue** [comment]
Added support for TR reading from each subject.
Ready to test

**Comment by trislett** [comment]
Hi Ilya,

How consistent is that method? It may be better to take it from the nifti
header using nibabel.

Cheers,

Tris

**Comment by marcbue** [comment]
Just to clarify:
It currently is taken via nibabel.
