### ISSUE TITLE
document number of voxels covered in each atlas region

### ISSUE THREAD

**Issue by ilyaveer** [mindandbrain/pipeline#9]
Good news: fslmeants will output a column of zeroes for atlas labels that are not covered in the input data.

For Marc: We therefore do not need to mask the atlas file with the bold mask before using fslmeants.

For Tris: Do you know a simple way in Python to extract the % voxels of an atlas label (region) that is covered in the 4D data? I could only do this in a very ugly way using shell script and fsl...

**Comment by trislett** [comment]
Here's the function. Please adjust accordantly.

```
def nonzero_atlas(input_image_path, seg_image_path):
	input_image = input_image_path
	in_img = nib.load(input_image)
	in_data = in_img.get_data()
	#binarize image
	in_data[in_data!=0] = 1

	seg_image = seg_image_path
	seg_img = nib.load(seg_image_path)
	seg_data = seg_img.get_data()

	masked = np.zeros_like(seg_data)
	masked[in_data!=0] = seg_data[in_data!=0]

	in_data = in_data.astype(np.uint8)

	label_number = []
	size_roi_data = []
	size_roi_atlas = []
	
	for label in np.unique(seg_data):
		if int(label)>0:
			label_number.append(label)
			size_roi_data.append(int(seg_data[masked==label].shape[0]))
			size_roi_atlas.append(int(seg_data[seg_data==label].shape[0]))

	out_arr = np.column_stack((label_number,size_roi_data))
	out_arr = np.column_stack((out_arr,size_roi_atlas))

	# column1, column2, column3
	# Label, n_data, n_atlas

	np.savetxt("output.csv", 
		out_arr,
		delimiter=',',
		fmt='%d')
```

**Comment by marcbue** [comment]
inputs are mni_bold_mask (func_preproc_wf - outputnode.bold_mask_mni, atlas_file)

In atlas_matrix (run.py) we change all the columns (labels) to NAN before calculating the correlation matrix that do not pass a threshold after executing the above function (e.g. 80%).

**Comment by marcbue** [comment]
the output.csv should be saved in intermediates/$(Atlas_name)_coverage.csv

**Comment by marcbue** [comment]
add column4 to output.csv that shows the ratio (n_data/n_atlas). % of voxels covered

**Comment by marcbue** [comment]
This should also be done for seeds and ICA maps,
Script has to be adjusted for these cases
In the end we do this for **all** atlases, seeds, and ica templates --> Loop over each

**Comment by marcbue** [comment]
Branch #Issue9 now has the atlas_coverage files and columns are excluded from the correlation matrix. Can be tested.

Question: Does the user set the threshold themselves in the gui? Currently I hardcoded 80%.

**Comment by ilyaveer** [comment]
Tested, works as should! For now it is okay to leave the threshold of 80% hardcoded.

Last to-do: Now cells in the correlation matrices are left empty when there is not more than 80% coverage. Can we have NaN for these cells instead?

**Comment by marcbue** [comment]
made the changes, nans are now shown in the csv, merged into dev

can this be closed?
